Ext.define('SSJT.view.person.PersonShowDetails', {
    extend: 'Ext.Panel',
    xtype: 'personshowdetails',

    cls: 'person-details',
    title: '详细信息',

    bind: {
        record: '{record}'
    },

    tpl: [
        '<div class="block-section">',
            '<div class="item">',
                '<div class="label">用户名:</div>',
                '<div class="value">{UserName}</div>',
            '</div>',
            '<div class="item">',
                '<div class="label">性别:</div>',
                '<div class="value">{Sex}</div>',
            '</div>',
            '<tpl if="Birthday">',
                '<div class="item">',
                    '<div class="label">生日</div>',
                    '<div class="value">{Birthday:date("F jS, Y")}</div>',
                    '<div class="extra">{Birthday:dateDiff(new Date())}</div>',
                '</div>',
            '</tpl>',
            '<div class="item">',
                '<div class="label">部门:</div>',
                '<div class="value">{Dname}</div>',
            '</div>',
            '<div class="item">',
                '<div class="label">职务:</div>',
                '<div class="value">{ZhiWu}</div>',
            '</div>',
            '<div class="item">',
                '<div class="label">岗位:</div>',
                '<div class="value">{Post}</div>',
            '</div>',
        '</div>',
        '<div class="block-section">',
            '<div class="item">',
                '<div class="label">学校:</div>',
                '<div class="value">{Education}</div>',
            '</div>',
            '<div class="item">',
                '<div class="label">水平:</div>',
                '<div class="value">{Levels}</div>',
            '</div>',
            '<div class="item">',
                '<div class="label">专业:</div>',
                '<div class="value">{Professional}</div>',
            '</div>',
            '<tpl if="Tel">',
                '<div class="item">',
                    '<div class="label">电话:</div>',
                    '<div class="value">{Tel}</div>',
                '</div>',
            '</tpl>',
            '<div class="item">',
                '<div class="label">邮箱:</div>',
                '<div class="value">{Email}</div>',
            '</div>',
            '<div class="item">',
                '<div class="label">住址:</div>',
                '<div class="value">{Address}</div>',
            '</div>',
        '</div>'
    ]
});
