Ext.define('SSJT.model.PersonalNote',{
    extend:'SSJT.model.Base',
    fields:[
        'NoteID',
        'NoteContent',
        {
            name:'Priority',
            type:'string',
            defaultValue:'H'
        },
        'NoteColor',
        {
            name:'LocationX',
            type:'int'
        },
        {
            name:'LocationY',
            type:'int'
        },
        {
            name:'Width',
            type:'int'
        },
        {
            name:'Height',
            type:'int'
        },
        {
            name:'IsShow',
            type:'string',
            defaultValue:'N'
        },
        'CreatorId',
        'CreatorName',
        {
            name:'CreateDate',
            type:'date',
            dateFormat:'Y-m-d H:i:s'
        },
        'UpdaterID',
        'UpdaterName',
        {
            name:'UpdateDate',
            type:'date',
            dateFormat:'Y-m-d H:i:s'
        },
        {
            name:'IsFinish',
            type:'string',
            defaultValue:'N'
        },
        {
            name:'FinishDate',
            type:'date',
            dateFormat:'Y-m-d H:i:s'
        },
        {
            name:'CustomID',
            calculate:function(data){
                return ComUtils.string2Hex(data.NoteID);
            }
        }
    ]

});