Ext.define('SSJT.view.mine.information.Container',{
    extend:'SSJT.view.widgets.Browse',
    xtype:'info_container',
    requires:[
        'SSJT.view.mine.information.InfoToolbar'
    ],
    tbar:{
        xtype:'info_toolbar'
    },
    controller:'info_container',
    layout:'card',
    items:[{
        xtype:'information_news'
    }]
})